theme="gruvbox"

[editor]
clipboard-provider="wayland"
gutters=["diff","line-numbers","spacer"]
auto-completion=true
completion-trigger-len = 1

[keys.normal]
a="insert_mode"

[keys.normal.space]
w=":write"
q=":quit!"

# [editor.indent-guides]
# render=true
# character="│"
# skip-levels=0

[editor.inline-diagnostics]
cursor-line = "info"
# other-lines = "error"
prefix-len = 2
max-diagnostics=1
