{ pkgs, config, ... }:

{
  programs.neovim = {
    enable = true;
    vimAlias = true;
    withRuby = true;
    withPython3 = true;
    initLua = ''
      require("config")
    '';
  };

  home.activation.setupNvim = config.lib.dag.entryAfter [ "writeBoundary" ] ''
    # init.lua is generated by programs.neovim above, so copy in only the
    # config modules and leave it alone.
    mkdir -p "$HOME/.config/nvim"
    rm -rf "$HOME/.config/nvim/lua" "$HOME/.config/nvim/plugin"
    cp -r ${./nvim}/lua "$HOME/.config/nvim/lua"
    chmod -R u+w "$HOME/.config/nvim/lua"
    if [ -d ${./nvim}/plugin ]; then
      cp -r ${./nvim}/plugin "$HOME/.config/nvim/plugin"
      chmod -R u+w "$HOME/.config/nvim/plugin"
    fi

    # Plugins are managed by lazy.nvim, which installs itself on first start.
  '';

  home.packages = with pkgs; [
    # Required by nvim-treesitter (main branch) to build parsers
    tree-sitter

    lua-language-server
    fish-lsp
    gopls
    ols
    typescript-language-server
    clang-tools
    pyright
    rust-analyzer
    jdt-language-server
  ];
}
